// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2WGachBuy1InlYXSw3IjUKZvBnK-fGxk',
    appId: '1:494197517948:web:eadbbf2fd26f0fc5a5a3f9',
    messagingSenderId: '494197517948',
    projectId: 'elendin-60',
    authDomain: 'elendin-60.firebaseapp.com',
    databaseURL: 'https://elendin-60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elendin-60.firebasestorage.app',
    measurementId: 'G-8P2L2WSS0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0GJOOLoiU4JcnlRliehSWZy5tiuLByI4',
    appId: '1:494197517948:android:fa6b50c2aa85cbbda5a3f9',
    messagingSenderId: '494197517948',
    projectId: 'elendin-60',
    databaseURL: 'https://elendin-60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elendin-60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbc2n7nUB5MQ9kIQJ3_RDb4VFlXiy_aUU',
    appId: '1:494197517948:ios:ae94a2b5561eb900a5a3f9',
    messagingSenderId: '494197517948',
    projectId: 'elendin-60',
    databaseURL: 'https://elendin-60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elendin-60.firebasestorage.app',
    androidClientId: '494197517948-2sinukl8cpm8del0p4bnkgc1imc2711l.apps.googleusercontent.com',
    iosClientId: '494197517948-l44phc0e01rpmclefu2jojaqb765pvs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.elendinFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbc2n7nUB5MQ9kIQJ3_RDb4VFlXiy_aUU',
    appId: '1:494197517948:ios:ae94a2b5561eb900a5a3f9',
    messagingSenderId: '494197517948',
    projectId: 'elendin-60',
    databaseURL: 'https://elendin-60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elendin-60.firebasestorage.app',
    androidClientId: '494197517948-2sinukl8cpm8del0p4bnkgc1imc2711l.apps.googleusercontent.com',
    iosClientId: '494197517948-l44phc0e01rpmclefu2jojaqb765pvs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.elendinFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2WGachBuy1InlYXSw3IjUKZvBnK-fGxk',
    appId: '1:494197517948:web:0b34222fa6893850a5a3f9',
    messagingSenderId: '494197517948',
    projectId: 'elendin-60',
    authDomain: 'elendin-60.firebaseapp.com',
    databaseURL: 'https://elendin-60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elendin-60.firebasestorage.app',
    measurementId: 'G-J84Y0NJVMK',
  );
}
